const FETCHING_SUCCESS_DEFINATION = 'add_data';
const FETCHING_LOADING_DEFINATION = 'fetching_data';
const FETCHING_FAIL_DEFINATION = 'fail_data';
const FETCHING_SUCCESS_EXAMPLES = 'add_examples';
const FETCHING_LOADING_EXAMPLES = 'fetching_examples';
const FETCHING_FAIL_EXAMPLES = 'fail_examples';
const FETCHING_SUCCESS_SYNONIMS = 'add_synonims';
const FETCHING_LOADING_SYNONIMS = 'fetching_synonims';
const FETCHING_FAIL_SYNONIMS = 'fail_synonims';
const FETCHING_SUCCESS_ANTONYMS = 'add_antonyms';
const FETCHING_LOADING_ANTONYMS = 'fetching_antonyms';
const FETCHING_FAIL_ANTONYMS = 'fail_antonyms';
const NEW_ERROR_ADDING = 'new_error_adding';
const RESET_NEW_ERROR_COUNT = 'reset_new_error_count';
const DELETE_ERROR_LIST = 'delete_error_list';
const MARK_AS_EXPORT = 'mark_as_export';
const UNMARK_AS_EXPORT = 'unmark_as_export';
const ADD_WORD_TO_FAVOURITE = 'add_word_to_fav';
const REMOVE_WORD_TO_FAVOURITE = 'REMOVE_word_to_fav';
const ADD_ALL_FV_WORD = 'add_all_fv_word';
export {
  ADD_ALL_FV_WORD,
  ADD_WORD_TO_FAVOURITE,
  REMOVE_WORD_TO_FAVOURITE,
  MARK_AS_EXPORT,
  UNMARK_AS_EXPORT,
  NEW_ERROR_ADDING,
  DELETE_ERROR_LIST,
  RESET_NEW_ERROR_COUNT,
  FETCHING_SUCCESS_DEFINATION,
  FETCHING_LOADING_DEFINATION,
  FETCHING_FAIL_DEFINATION,
  FETCHING_SUCCESS_EXAMPLES,
  FETCHING_LOADING_EXAMPLES,
  FETCHING_FAIL_EXAMPLES,
  FETCHING_SUCCESS_SYNONIMS,
  FETCHING_LOADING_SYNONIMS,
  FETCHING_FAIL_SYNONIMS,
  FETCHING_SUCCESS_ANTONYMS,
  FETCHING_LOADING_ANTONYMS,
  FETCHING_FAIL_ANTONYMS,
};
